<div class="form-container">
  <h2>Créer un compte</h2>
  <form method="post">
    <label for="inputFirstName">Prénom <span class="error"><?=$userMessages['requiredFirstName'] ?? '' ?></span></label>
    <input name="firstName" id="inputFirstName" type="text" value="<?=$data['firstName'] ?? '' ?>" />

    <label for="inputLastName">Nom <span class="error"><?=$userMessages['requiredLastName'] ?? '' ?></span></label>
    <input name="lastName" id="inputLastName" type="text" value="<?=$data['lastName'] ?? '' ?>" />

    <label for="inputLogin">Login <span class="error"><?=$userMessages['requiredLogin'] ?? '' ?></span></label>
    <input name="login" id="inputLogin" type="text" value="<?=$data['login'] ?? '' ?>" />

    <label for="inputPassword">Mot de passe <span class="error"><?=$userMessages['requiredPassword'] ?? '' ?></span></label>
    <input name="password" id="inputPassword" type="password" />

    <label for="checkboxIsAdmin">Est Admin</label>
    <input name="isAdmin" id="checkboxIsAdmin" type="checkbox" <?=isset($data['isAdmin']) && $data['isAdmin'] ? 'checked' : '' ?> />

    <input type="submit" name="accountSubmit" value="Enregistrer" />
  </form>
</div>
