<?php if (!empty($errors)) : ?>

    <div class="arlert alert-danger">
        <p>Vous devez remplir tout les champs du formulaire</p>
        <ul>
            <?php foreach ($errors as $error) : ?>
                <li><?= $error ?></li>
            <?php endforeach ?>
        </ul>

    </div>
<?php endif ?>
<br>

<section class="article" style="width: 50%; margin-left:20%">
    <p><strong><?= $pageTitle ?></strong></p>

    <br />
    <form method="POST" class="form-group">
        <div class="form-group">
            <input type="text" name="title" placeholder="Titre"></input>
        </div>
        <div class="form-group">
            <textarea id="tiny" name="content" id="" placeholder="Contenu"></textarea>
            <div>
                <br />

                <button class="btn btn-primary" type="submit" id="form-submit" name="author_id" value="<?= $_SESSION['id'] ?>">Poster</button>
    </form>
</section>