<div class="admin-container">
  <p>Bienvenue sur votre Admin !</p>
  <p>Bonjour <?= $_SESSION['firstName'] ?> <?= $_SESSION['lastName'] ?></p>
  <a href="?page=admin&action=listAccounts">Liste des comptes</a>
  <br />
  <a href="?page=admin&action=createAccount">Créer un compte</a>
  <br>
  <a href="?page=admin&action=listArticle">articles</a>
  <br>
  <a href="?page=admin&action=addArticle">creer articles</a>
  <br>
  <a href="?page=admin&action=createCategorie">Créer categorie</a>

</div>