<?php

use Src\core\Secu;
?>

<!-- header starts -->
<div class="header">
   <div class="header__left">
      <a href="#"><img src="../public/assets/img/logo.png" alt="logo"> </a>
   </div>

   <div class="header__middle">
      <div class="header__option active">
         <a href="?page=admin&action=admin"> <i class="fas fa-home"></i> </a>
      </div>
      <div class="header__option">
         <a href="?page=admin&action=listAccounts"><i class="fas fa-users"></i></a>
      </div>
   </div>

   <div class="header__right">
      <div class="header__info">
         <?php
         if ($_SESSION['photo'] === '') {
            echo '<img class="user__avatar" src="../public/assets/img/pic_profils/avatar.png" alt="photo de profil">';
         } else {
            echo '<img class="user__avatar"  src="' . $_SESSION['photo'] . ' " alt="photo de profil">';
         }
         ?>
         <h3><?= $_SESSION['firstName'] ?> <?= $_SESSION['lastName'] ?></h3>

      </div>
      <a href="?page=admin&action=deconnexion"><i class="fas fa-times-circle"></i></a>
   </div>
</div>
<div class="cont">
   <label class="theme-switch" for="checkbox">
      <input type="checkbox" id="checkbox" />
   </label>
</div>
<!-- header ends -->

<!-- main body starts -->
<div class="global">
   <!-- sidebar starts -->
   <div class="sidebar">
      <div class="sidebar-side">
         <?php
         if ($_SESSION['photo'] === '') {
            echo '<img class="user__avatar post__avatar" src="../public/assets/img/pic_profils/avatar.png" alt="photo de profil">';
         } else {
            echo '<img class="user__avatar post__avatar"  src="' . $_SESSION['photo'] . ' " alt="photo de profil">';
         }
         ?>
         <h2><?= $_SESSION['firstName'] ?> <?= $_SESSION['lastName'] ?></h2>
      </div>
      <h3>Mes informations</h3>
      <p>Role: admin </p>
      <div class="sidebar-side">
         <div class="sidebar-side__menu">
        <a href="?page=admin&action=listAccounts"><i class="fas fa-users"> Users</i></a>
        <a href="?page=admin&action=createAccount"><i class="fas fa-user-plus"> Ajouter user</i></a>
        <a href="?page=admin&action=deconnexion"><i class="fas fa-times-circle"> Deconnexion</i></a>
         </div>
      </div>

   </div>


   <div class="menu-toggle">
      <div class="opacity"></div>
      <div class="hamburger">
         <span></span>
      </div>
   </div>
   <div class="content-articles">
      <div class="articlesend">
         <div class="element__title">
            <h2>Modifier article</h2>
         </div>
         <div class="articlesend__top">
            <form method="POST">
               <label for="title">Titre:</label>
               <input name="title" id="title" placeholder="Ici le Nouveau Titre" value="<?= $article['title'] ?>">
               <label for="title">Contenu:</label>
               <textarea rows="5" cols="33" class="articlesend__input" name="content" placeholder="Contenu"><?= $article['content'] ?> </textarea>
         </div>
         <div class="articlesend__bottom">
            <div class="articlesend__option">
               <button class="icon--pur" type="submit" id="form-submit"><i class="fas fa-paper-plane"></i></button>
            </div>
         </div>
         </form>

      </div>
   </div>
</div>