<header>
    <div class="menucontainer">

        <nav class="navbar " id="menu">
            <div class="menucontainer__burger" id="burger">
                <i class="fas fa-bars open"></i>
                <i class="fas fa-times close"></i>
            </div>
            <a href="#" class="navbar__menu--logo">ENCODEURS </a>
            <ul class="navbar__menu">
                <input type="search" name="article" id="">
                <li class="navbar__menu--item"><a href="?page=admin&action=deconnexion" class="navbar__menu--link ">Deconnexion</a></li>
                <input type="button" class="btn btn-outline-primary" value="back" onclick="history.go(-1)">
            </ul>
            <div class="burger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </div>
</header>

<section class="eddit_article" style="width: 50%; margin-left:20%">
    <p><strong><?= $pageTitle ?></strong></p>
    <br />
    <form method="POST">
        <div class="form-group">
            <input name="title" placeholder="Ici le Nouveau Titre" value="<?= $article['title'] ?>"></input>
        </div>
        <div class="form-group">
            <textarea id="tiny" name="content" placeholder="Contenu"><?= $article['content'] ?></textarea>
        </div>
        <br />
        <button class="btn btn-primary" type="submit" id="form-submit">Poster</button>
    </form>
    <br />
</section>