<header>
    <div class="menucontainer">

        <nav class="navbar " id="menu">
            <div class="menucontainer__burger" id="burger">
                <i class="fas fa-bars open"></i>
                <i class="fas fa-times close"></i>
            </div>
            <a href="#" class="navbar__menu--logo">LeS EnCoDeUrS dE MoUcHe </a>
            <ul class="navbar__menu">
                <input type="search" name="article" id="">
                <li class="navbar__menu--item"><a href="?page=admin&action=deconnexion" class="navbar__menu--link ">Deconnexion</a></li>
            </ul>
            <div class="burger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </div>
</header>
<small>Ecrit le <?= $article['created_date']  ?></small>
<h1><?= $article['title'] ?></h1>
<p><?= $article['content'] ?></p>
<hr>

<?php if (count($commentaires) === 0) : ?>
    <h2> vous pouvez reagissez </h2>
<?php else : ?>
    <h2>Il y a <?= count($commentaires) ?> commentaires : </h2>
    <?php foreach ($commentaires as $commentaire) : ?>
        <h3>Commentaire de <?= $commentaire['login'] ?></h3>
        <blockquote>
            <em><?= $commentaire['content'] ?></em>
        </blockquote>
        <a href="delete-comment.php?id=<?= $commentaire['id'] ?>" onclick="return window.confirm(`Êtes vous sûr de vouloir supprimer ce commentaire ?!`)">Supprimer</a>
    <?php endforeach ?>
<?php endif ?>

<form method="POST">
    <h3>votre commentaire !</h3>
    <input type="text" name="comment" placeholder=" Commenter .... !">
    <input type="hidden" name>
    <button>Commenter !</button>
</form>