<h1>Nos articles</h1>
<a href="?page=admin&action=createAccount">ajouter ➕</a>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid unde autem quis doloribus quaerat. Explicabo omnis officia veniam optio in labore animi quos veritatis impedit eius, quis corporis laborum sequi.
<?php foreach ($articles as $article) : ?>
    <h2><?= $article->getTitle() ?></h2>
    <p><?= $article->getContent() ?></p>
    <p><?= $article->getAuthor_id() ?></p>

    <a href="<?= ADMIN_DEL_ART . $article->getId() ?>" onclick="return window.confirm(`Êtes vous sur de vouloir supprimer cet article ?!`)">➕</a>
    <a class="icon-link" href="?page=admin&action=deleteAccount&id=<?= $account->getId() ?>">🗑️</a>
<?php endforeach ?>