<h1>Nos articles</h1>
<a href="?page=admin&action=addArticle">ajouter ➕</a>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid unde autem quis doloribus quaerat. Explicabo omnis officia veniam optio in labore animi quos veritatis impedit eius, quis corporis laborum sequi.
<a class="icon-link" href="?page=admin&action=editAccount&id=<?= $account->getId() ?>">➕</a>
<?php foreach ($articles as $article) : ?>
    <h2><?= $article->getTitle() ?></h2>
    <p><?= $article->getContent() ?></p>
    <a href="?page=admin&action=addComment&id=<?= $comment->getId() ?>" >➕</a>
    <a href="?page=admin&action=modifyArticle&id=<?= $article->getId() ?>" >Modifier</a>
    <a class="icon-link" href="?page=admin&action=deleteArticle&id=<?= $article->getId() ?>">🗑️</a>
<?php endforeach ?>