<?php require_once '../config/init.php';
?>

<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="icon" type="image/x-icon" href="<?= PUBLIC_HOME; ?>img/favi.ico">
   <link rel="stylesheet" href="<?= PUBLIC_HOME; ?>css/style.css">
   <link rel="stylesheet" href="<?= PUBLIC_HOME; ?>/fontawesome/css/all.css">
   <title><?= $title ?? 'Fun with Code' ?></title>
</head>

<body>
   <main>
      <?= $pageContent; ?>
   </main>
   <script src="<?= PUBLIC_HOME; ?>js/main.js"></script>

</body>

</html>