<?php require_once '../config/init.php';
?>

<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="<?= PUBLIC_HOME; ?>css/style.css">
   <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />


   <title>Les encodeurs </title>
</head>

<body>
     
   <!-- <input type="button" class="btn btn-outline-primary" value="back" onclick="history.go(-1)"> -->
   <!-- <a class="btn btn-outline-primary" href="?page=admin&action=deconnexion" style="float:right;margin: 0px 20px;">deconnexion</a> -->
   <?= $pageContent; ?>
   </main>
   <script src="<?= PUBLIC_HOME; ?>js/main.js"></script>
</body>

</html>