<div class="form-container">
  <h2>Login</h2>
    <span class="error"><?= $userMessages['loginFail'] ?></span>
    <form method="post">
      <label for="inputLogin">Login <span class="error"><?=$userMessages['requiredLogin'] ?></span></label>
      <input name="formLogin" id="inputLogin" type="text" />

      <label for="inputPassword">Mot de passe <span class="error"><?=$userMessages['requiredPassword'] ?></span></label>
      <input name="formPassword" id="inputPassword" type="password" />

      <input type="submit" name="loginSubmit" value="Login" />
    </form>
</div>
